name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Create .env file
      run: |
        echo "VITE_URL_API=${{ secrets.VITE_URL_API }}" >> .env
    - name: Login to docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build the Docker image
      run: docker build -t asrulkadir/travel-article-app:latest .  --platform=linux/amd64
    - name: Push the Docker image
      run: docker push asrulkadir/travel-article-app:latest
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          cd ~/travel-article-app
          docker compose up -d
